Desarrollo del Login - Primeros pasos
GabrielEstebanSalvatore/yourside pull request #9
Opened 2021-09-21 15:02 UTC by MatiasMMaldon01

En esta pull request se modifica el entorno Mobile de la aplicación. 
* Se modifica la pagina home agregando un side-menu y presentando los artículos por medio de cards.
* Se crea las paginas signup y login para que los clientes puedan registrarse e iniciar sesión respectivamente.
* Se crean los respectivos servicios(clientService, articleService y authService), para conectar el front-end con el API desarrollada con anterioridad.
* Se crean los modelos (clientModel y articleModel).
* Se crea el guard para poder bloquear las rutas (se le dará uso conforme la aplicación vaya desarrollándose) cuando el cliente no se logeea.
* Se crea un interceptor para interceptar y/o mutar las solicitudes y respuestas, para manejar los errores y para poder crear un header que es utilizado para validar el token del cliente.(mutara en el transcurso del desarrollo).

2021-09-22 14:01 UTC, GabrielEstebanSalvatore commented on mobile-ys/src/app/app-routing.module.ts
>          path: 'signin',
Hi Maty, I think there is a discrepancy here

2021-09-22 14:04 UTC, GabrielEstebanSalvatore commented on mobile-ys/src/app/pages/signup/signup-routing.module.ts
Maty remember to be consistent with indentation ;D

2021-09-22 14:12 UTC, GabrielEstebanSalvatore commented on mobile-ys/src/app/pages/login/login.page.ts
>        error => console.log(error)
It may not be very important now, but later we can work a bit with the exceptions and errors handling

2021-09-23 01:56 UTC, camilosanchezdev requested changes
All good.
Tasks:
1. Pasar servicios y models a shared
2. Crear .env y definir la ruta de la API

2021-09-23 01:56 UTC, camilosanchezdev commented on mobile-ys/src/app/core/models/ArticleModel.ts
> +export interface Article{
Los Models los ubicaremos en shared/models porque los compartimos en todas las pantallas. La carpeta Core la utilizamos para lo más abstracto, como la comunicación con el backend o el estado general de la app.

2021-09-23 01:56 UTC, camilosanchezdev commented on mobile-ys/src/app/core/models/clientModel.ts
> +export interface Cliente{
Same here, pasar a shared/models

2021-09-23 01:56 UTC, camilosanchezdev commented on mobile-ys/src/app/core/services/articlesService/article.service.ts
> +import { HttpClient } from '@angular/common/http';
Estos servicios tienen que ir en shared/services. En el core crearemos un solo servicio, del cual heredarán los servicios de shared/services. En donde podremos inyectar una sola vez el HttpModule y crear los métodos básicos de un crud (GetAll, GetById, Create, Delete).

2021-09-23 01:56 UTC, camilosanchezdev commented on mobile-ys/src/app/core/services/clientService/client.service.ts
> +import { Injectable } from '@angular/core';
Pasar service a shared/service.
Crea un archivo de environment para tener acceso a la API_URL y evitamos tener que declararla en cada servicio

2021-10-05 19:24 UTC, camilosanchezdev approved these changes

2021-10-05 19:24 UTC, merged